inherit_gem:
  rubocop-shopify: rubocop.yml

require:
 - rubocop-sorbet
 - rubocop-rake

AllCops:
  NewCops: disable
  SuggestExtensions: false
  TargetRubyVersion: 3.0

Naming/FileName:
  Exclude:
  - "lib/ruby-lsp-rspec.rb"

Sorbet/FalseSigil:
  Enabled: false

Sorbet/TrueSigil:
  Enabled: true
  Include:
    - "test/**/*.rb"
  Exclude:
    - "**/*.rake"
    - "lib/**/*.rb"

Sorbet/StrictSigil:
  Enabled: true
  Include:
    - "lib/**/*.rb"
  Exclude:
    - "**/*.rake"
    - "test/**/*.rb"

Style/StderrPuts:
  Enabled: true

Style/MethodCallWithArgsParentheses:
  Enabled: false
